import { geoContains } from "d3-geo";
import { feature } from "topojson-client";
import countriesTopology from "world-atlas/countries-110m.json";
import type { Feature, FeatureCollection, Geometry, MultiPolygon, Polygon, Position } from "geojson";
import { type ContinentId } from "./continent-data";

export type CountryFeature = Feature<Polygon | MultiPolygon, { name?: string }>;

const countryFeatureCollection = feature(
  countriesTopology as never,
  (countriesTopology as { objects: { countries: unknown } }).objects.countries as never,
) as unknown as FeatureCollection<Polygon | MultiPolygon, { name?: string }>;

export const COUNTRY_FEATURES = countryFeatureCollection.features;

const COUNTRY_CONTINENT: Record<string, ContinentId> = {
  Afghanistan: "asia",
  Albania: "europe",
  Algeria: "africa",
  "American Samoa": "australia",
  Andorra: "europe",
  Angola: "africa",
  Anguilla: "north-america",
  Antarctica: "antarctica",
  "Antigua and Barb.": "north-america",
  Argentina: "south-america",
  Armenia: "asia",
  Aruba: "north-america",
  "Ashmore and Cartier Is.": "australia",
  Australia: "australia",
  Austria: "europe",
  Azerbaijan: "asia",
  Bahamas: "north-america",
  Bahrain: "asia",
  Bangladesh: "asia",
  Barbados: "north-america",
  Belarus: "europe",
  Belgium: "europe",
  Belize: "north-america",
  Benin: "africa",
  Bermuda: "north-america",
  Bhutan: "asia",
  Bolivia: "south-america",
  "Bosnia and Herz.": "europe",
  Botswana: "africa",
  "Br. Indian Ocean Ter.": "africa",
  Brazil: "south-america",
  "British Virgin Is.": "north-america",
  Brunei: "asia",
  Bulgaria: "europe",
  "Burkina Faso": "africa",
  Burundi: "africa",
  "Cabo Verde": "africa",
  Cambodia: "asia",
  Cameroon: "africa",
  Canada: "north-america",
  "Cayman Is.": "north-america",
  "Central African Rep.": "africa",
  Chad: "africa",
  Chile: "south-america",
  China: "asia",
  Colombia: "south-america",
  Comoros: "africa",
  Congo: "africa",
  "Cook Is.": "australia",
  "Costa Rica": "north-america",
  Croatia: "europe",
  Cuba: "north-america",
  Curaçao: "north-america",
  Cyprus: "asia",
  Czechia: "europe",
  "Côte d'Ivoire": "africa",
  "Dem. Rep. Congo": "africa",
  Denmark: "europe",
  Djibouti: "africa",
  Dominica: "north-america",
  "Dominican Rep.": "north-america",
  Ecuador: "south-america",
  Egypt: "africa",
  "El Salvador": "north-america",
  "Eq. Guinea": "africa",
  Eritrea: "africa",
  Estonia: "europe",
  Ethiopia: "africa",
  "Faeroe Is.": "europe",
  "Falkland Is.": "south-america",
  Fiji: "australia",
  Finland: "europe",
  "Fr. Polynesia": "australia",
  "Fr. S. Antarctic Lands": "antarctica",
  France: "europe",
  Gabon: "africa",
  Gambia: "africa",
  Georgia: "asia",
  Germany: "europe",
  Ghana: "africa",
  Greece: "europe",
  Greenland: "north-america",
  Grenada: "north-america",
  Guam: "australia",
  Guatemala: "north-america",
  Guernsey: "europe",
  Guinea: "africa",
  "Guinea-Bissau": "africa",
  Guyana: "south-america",
  Haiti: "north-america",
  "Heard I. and McDonald Is.": "antarctica",
  Honduras: "north-america",
  "Hong Kong": "asia",
  Hungary: "europe",
  Iceland: "europe",
  India: "asia",
  "Indian Ocean Ter.": "australia",
  Indonesia: "asia",
  Iran: "asia",
  Iraq: "asia",
  Ireland: "europe",
  "Isle of Man": "europe",
  Israel: "asia",
  Italy: "europe",
  Jamaica: "north-america",
  Japan: "asia",
  Jersey: "europe",
  Jordan: "asia",
  Kazakhstan: "asia",
  Kenya: "africa",
  Kiribati: "australia",
  Kosovo: "europe",
  Kuwait: "asia",
  Kyrgyzstan: "asia",
  Laos: "asia",
  Latvia: "europe",
  Lebanon: "asia",
  Lesotho: "africa",
  Liberia: "africa",
  Libya: "africa",
  Liechtenstein: "europe",
  Lithuania: "europe",
  Luxembourg: "europe",
  Macao: "asia",
  Macedonia: "europe",
  Madagascar: "africa",
  Malawi: "africa",
  Malaysia: "asia",
  Maldives: "asia",
  Mali: "africa",
  Malta: "europe",
  "Marshall Is.": "australia",
  Mauritania: "africa",
  Mauritius: "africa",
  Mexico: "north-america",
  Micronesia: "australia",
  Moldova: "europe",
  Monaco: "europe",
  Mongolia: "asia",
  Montenegro: "europe",
  Montserrat: "north-america",
  Morocco: "africa",
  Mozambique: "africa",
  Myanmar: "asia",
  "N. Cyprus": "asia",
  "N. Mariana Is.": "australia",
  Namibia: "africa",
  Nauru: "australia",
  Nepal: "asia",
  Netherlands: "europe",
  "New Caledonia": "australia",
  "New Zealand": "australia",
  Nicaragua: "north-america",
  Niger: "africa",
  Nigeria: "africa",
  Niue: "australia",
  "Norfolk Island": "australia",
  "North Korea": "asia",
  Norway: "europe",
  Oman: "asia",
  Pakistan: "asia",
  Palau: "australia",
  Palestine: "asia",
  Panama: "north-america",
  "Papua New Guinea": "australia",
  Paraguay: "south-america",
  Peru: "south-america",
  Philippines: "asia",
  "Pitcairn Is.": "australia",
  Poland: "europe",
  Portugal: "europe",
  "Puerto Rico": "north-america",
  Qatar: "asia",
  Romania: "europe",
  Russia: "europe",
  Rwanda: "africa",
  "S. Geo. and the Is.": "antarctica",
  "S. Sudan": "africa",
  "Saint Helena": "africa",
  "Saint Lucia": "north-america",
  Samoa: "australia",
  "San Marino": "europe",
  "Saudi Arabia": "asia",
  Senegal: "africa",
  Serbia: "europe",
  Seychelles: "africa",
  "Siachen Glacier": "asia",
  "Sierra Leone": "africa",
  Singapore: "asia",
  "Sint Maarten": "north-america",
  Slovakia: "europe",
  Slovenia: "europe",
  "Solomon Is.": "australia",
  Somalia: "africa",
  Somaliland: "africa",
  "South Africa": "africa",
  "South Korea": "asia",
  Spain: "europe",
  "Sri Lanka": "asia",
  "St-Barthélemy": "north-america",
  "St-Martin": "north-america",
  "St. Kitts and Nevis": "north-america",
  "St. Pierre and Miquelon": "north-america",
  "St. Vin. and Gren.": "north-america",
  Sudan: "africa",
  Suriname: "south-america",
  Sweden: "europe",
  Switzerland: "europe",
  Syria: "asia",
  "São Tomé and Principe": "africa",
  Taiwan: "asia",
  Tajikistan: "asia",
  Tanzania: "africa",
  Thailand: "asia",
  "Timor-Leste": "asia",
  Togo: "africa",
  Tonga: "australia",
  "Trinidad and Tobago": "north-america",
  Tunisia: "africa",
  Turkey: "asia",
  Turkmenistan: "asia",
  "Turks and Caicos Is.": "north-america",
  "U.S. Virgin Is.": "north-america",
  Uganda: "africa",
  Ukraine: "europe",
  "United Arab Emirates": "asia",
  "United Kingdom": "europe",
  "United States of America": "north-america",
  Uruguay: "south-america",
  Uzbekistan: "asia",
  Vanuatu: "australia",
  Vatican: "europe",
  Venezuela: "south-america",
  Vietnam: "asia",
  "W. Sahara": "africa",
  "Wallis and Futuna Is.": "australia",
  Yemen: "asia",
  Zambia: "africa",
  Zimbabwe: "africa",
  eSwatini: "africa",
  Åland: "europe",
};

export function getCountryContinentId(feature: CountryFeature) {
  const name = feature.properties?.name;
  return name ? COUNTRY_CONTINENT[name] ?? null : null;
}

export function getContinentIdAtLngLat(lng: number, lat: number) {
  const point: [number, number] = [lng, lat];
  const country = COUNTRY_FEATURES.find((entry) => geoContains(entry, point));
  return country ? getCountryContinentId(country) : null;
}

export function getContinentCountryFeatures(continentId: ContinentId) {
  return COUNTRY_FEATURES.filter((entry) => getCountryContinentId(entry) === continentId);
}

export function getGeometryRings(geometry: Geometry): Position[][] {
  if (geometry.type === "Polygon") return geometry.coordinates as Position[][];
  if (geometry.type === "MultiPolygon") return (geometry.coordinates as Position[][][]).flat();
  return [];
}
